remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentación

nombres: Andrés Baldur Tamayo Marín
submodulo: Lógica de Programación
periodo: 2023-2
url_foto: https://firebasestorage.googleapis.com/v0/b/fotogit-b823c.appspot.com/o/Baldur1.jpg?alt=media&token=8a356b7d-9640-4167-af58-f898a318049a

